name: Deploy Module

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of github environment. Environment must contain env vars ETHERSCAN_API_KEY, RPC_URL, PRIVATE_KEY, WALLET_ADDRESS, REGISTRAR, FEE_SETTINGS_OWNER.'
        required: true
      chainid:
        description: 'Chain id number. Must correspond with given environment - i.e. environment = "rinkeby", chainid = "4".'
        required: true
      overwrite:
        description: 'Enter "dontoverwrite", or "overwrite" to deploy even if core contracts already have addresses in addresses/<chain-id>.json file.'
        required: true
      module_name:
        description: 'Name of contract in solidity file, i.e. AsksV1_1'
        required: true
      module_path:
        description: 'Starting from modules folder, i.e Asks/V1.1/AsksV1_1.sol"
        required: true
      constructor_abi:
        description: 'Constructor abi, i.e. constructor(address,string)'
        required: true
      constructor_args:
        description: 'Arbitrary constructor args, exactly how you'd pass them into cli. i.e. 0x123...789 "This is an arg with spaces"'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Build contracts
        run: forge build
      - name: Run deploy script
        run: bash ./deploy/deploy-module.sh ${{ github.event.inputs.overwrite }} ${{ github.event.inputs.module_path }} ${{ github.event.inputs.module_name }} ${{ github.event.inputs.constructor_abi }} ${{ github.event.inputs.constructor_args }}
      - name: Push new addresses
        uses: EndBug/add-and-commit@v9
        with:
          add: addresses/${{ github.event.inputs.chainid }}.json
          message: 'Commit from Github Actions (deploy core)'
          new_branch: main
          pathspec_error_handling: ignore
    env:
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      CHAIN_ID: ${{ github.event.inputs.chainid }}
      RPC_URL: ${{ secrets.RPC_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
      REGISTRAR: ${{ secrets.REGISTRAR }}
      FEE_SETTINGS_OWNER: ${{ secrets.FEE_SETTINGS_OWNER }}
