name: Deploy Core

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of github environment. Environment must contain env vars ETHERSCAN_API_KEY, CHAIN_ID, RPC_URL, PRIVATE_KEY, WALLET_ADDRESS, REGISTRAR, FEE_SETTINGS_OWNER.'
        required: true
      overwrite:
        description: 'Must equal "overwrite" or "dontoverwrite". "overwrite" will deploy new contracts even if core contracts already have addresses in addresses/<chain-id>.json file.'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run deploy script
        run: bash ./deploy/deploy-core.sh ${{ github.event.inputs.overwrite }}
    env:
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      CHAIN_ID: ${{ secrets.CHAIN_ID }}
      RPC_URL: ${{ secrets.RPC_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
      REGISTRAR: ${{ secrets.REGISTRAR }}
      FEE_SETTINGS_OWNER: ${{ secrets.FEE_SETTINGS_OWNER }}
 
