name: Deploy Core

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of github environment. Environment must contain env vars ETHERSCAN_API_KEY, RPC_URL, PRIVATE_KEY, WALLET_ADDRESS, REGISTRAR, FEE_SETTINGS_OWNER.'
        required: true
      chainid:
        description: 'Chain id number. Must correspond with given environment - i.e. environment = "rinkeby", chainid = "4".'
        required: true
      overwrite:
        description: 'Enter "overwrite" to deploy even if core contracts already have addresses in addresses/<chain-id>.json file.'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Build contracts
        run: forge build
      - name: Run deploy script
        run: bash ./deploy/deploy-core.sh ${{ github.event.inputs.overwrite }}
      - name: Push new addresses
        uses: EndBug/add-and-commit@v9
        with:
          add: addresses/${{ github.event.inputs.chainid }}.json
          message: 'Commit from Github Actions (deploy core)'
          new_branch: main
          pathspec_error_handling: ignore
    env:
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      CHAIN_ID: ${{ github.event.inputs.chainid }}
      RPC_URL: ${{ secrets.RPC_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
      REGISTRAR: ${{ secrets.REGISTRAR }}
      FEE_SETTINGS_OWNER: ${{ secrets.FEE_SETTINGS_OWNER }}
 
